### ISSUE TITLE
Issues with parsing ens

### ISSUE THREAD

**Issue by iainnash** [Anish-Agnihotri/tweetdrop#1]
Hey! I've integrated a fork of this library into https://github.com/iainnash/ens2airdrop ens2airdrop and found some issues with it:

1. .Eth is not recognized: changed the ens regex to support case insensitive matches
2. people incorrectly uppercase ens names, so it does a search for both the exact case and lowercase versions
3. Regex for detecting ens names doesn't handle cases where the name is unicode or non-ascii.
4. Invalid addresses are still added to the result if they follow any sort of 0xNNN format, added in an ethers `isAddress(str)` check to determine if invalid/valid.

These all are fixed in the forked scraper https://github.com/iainnash/ens2airdrop/blob/main/scraper/scraper.ts here.

**Comment by Anish-Agnihotri** [comment]
Thank you boss, merged in #3.
